# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    env:
      digimon_1: "Agumon"
      digimon_2: "MetalGreymon"
      digimon_3: "WarGreymon"

    runs-on: ubuntu-latest

    steps:
      - name: Display a message
        run: echo Hello World !
      - name: Display best digimons
        run: |
          echo It is first dig-evolution ${{env.digimon_1}} !
          echo It is second dig-evolution ${{env.digimon_2}} !
          echo It is third dig-evolution ${{env.digimon_3}} !
      - name: Display data workflow
        run: |
          echo Github actor is: $GITHUB_ACTOR
          echo Github repository is: $GITHUB_REPOSITORY